import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.JPanel;

public class PlayerContainer extends javax.swing.JPanel
{
    private Player player;
    
    /**
     * Creates new form PlayerContainer
     */
    public PlayerContainer()
    {
        initComponents();
    }
    
    public void setCardOne()
    {
        cardOneLabel.setText(player.getCurrentHand()[0].toString());
    }
    
    public void setCardTwo()
    {
        cardTwoLabel.setText(player.getCurrentHand()[1].toString());
    }
        
    public Player getPlayer()
    {
        return player;
    }
    
    public void setPlayer(Player player)
    {
        this.player = player;
    }
    
    public void updateName()
    {
        this.playerNameLabel.setText(player.getName());
    }
    
    public void updateMoney()
    {
        this.playerMoneyLabel.setText(Double.toString(player.getMoney()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        playerNameLabel = new javax.swing.JLabel();
        playerMoneyLabel = new javax.swing.JLabel();
        cardOneLabel = new javax.swing.JLabel();
        cardTwoLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        playerNameLabel.setText("Player:");

        playerMoneyLabel.setText("Money");

        cardOneLabel.setText("Card One");

        cardTwoLabel.setText("Card Two");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(playerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerMoneyLabel)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardTwoLabel)
                    .addComponent(cardOneLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(cardOneLabel)
                .addGap(31, 31, 31)
                .addComponent(cardTwoLabel)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNameLabel)
                    .addComponent(playerMoneyLabel))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardOneLabel;
    private javax.swing.JLabel cardTwoLabel;
    private javax.swing.JLabel playerMoneyLabel;
    private javax.swing.JLabel playerNameLabel;
    // End of variables declaration//GEN-END:variables
}
